name: evnto
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ui
  intl: ^0.19.0
  another_flushbar: ^1.12.30
  flutter_native_splash: ^2.3.7
  flutter_svg: ^2.0.9
  otp_text_field: ^1.1.3

  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  # State Management
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  equatable: ^2.0.5

  # Localization
  flutter_localizations:
    sdk: flutter

  # Responsive
  flutter_screenutil: ^5.9.0

  # Service Locator
  get_it: ^7.6.4

  # Network
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1

  # Local Database
  shared_preferences: ^2.2.1
  internet_connection_checker: ^2.0.0

  # Code Generation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Encryption
  envied: ^0.5.4+1
  flutter_secure_storage: ^4.2.1

  # Others
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.3+1
  syncfusion_flutter_datepicker: ^26.2.8
  shimmer: ^3.0.0
  bloc_test: ^9.1.7


dev_dependencies:
  flutter_lints: ^4.0.0

  # Testing
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter

  # Code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true
  assets:
  #  - assets/images/
    - assets/icons/
    - assets/designs/
    - assets/fonts/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets\fonts\quicksand\Quicksand-Light.ttf
          weight: 300
        - asset: assets\fonts\quicksand\Quicksand-Regular.ttf
          weight: 400
        - asset: assets\fonts\quicksand\Quicksand-Medium.ttf
          weight: 500
        - asset: assets\fonts\quicksand\Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\quicksand\Quicksand-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  output_dir: lib/core/localization/generated
  arb_dir: lib/core/localization/l10n

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants/
  filename: app_assets.dart
  field_prefix:

flutter_native_splash:
  image: assets\images\splash_img.png
  color: "#ffffff"
  android: true
  ios: true
  android_12:
    image: assets\images\splash_img.png
    color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_backgorund: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
